import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { type ExecutionRole, type RequestedExecution, validateRequestedExecution } from "./executionRouting";

export const PROGRAM_MANIFEST_VERSION = 1;
export interface ProgramManifest { version: typeof PROGRAM_MANIFEST_VERSION; programId: string; repositories: Array<{ id: string; owner: string; name: string }>; milestones: Array<{ id: string; repositoryId: string; dependsOn?: string[]; routing?: Partial<Record<ExecutionRole, ExecutionRouteInput>> }>; routing: { defaults: Partial<Record<ExecutionRole, ExecutionRouteInput>> }; }
export type ExecutionRouteInput = Omit<RequestedExecution, "role" | "allowFallback"> & { allowFallback?: boolean };
export function loadProgramManifest(filePath: string): ProgramManifest { const raw = readFileSync(resolve(filePath), "utf8").replace(/^\uFEFF/, ""); let parsed: unknown; try { parsed = JSON.parse(raw); } catch (error) { throw new Error(`Invalid ProgramManifest JSON: ${filePath}`, { cause: error }); } return validateProgramManifest(parsed); }
export function validateProgramManifest(value: unknown): ProgramManifest { if (!record(value)) throw new Error("ProgramManifest must be an object."); exactKeys(value, ["version", "programId", "repositories", "milestones", "routing"], "ProgramManifest"); if (value.version !== PROGRAM_MANIFEST_VERSION) throw new Error(`ProgramManifest.version must be ${PROGRAM_MANIFEST_VERSION}.`); string(value.programId, "ProgramManifest.programId"); if (!Array.isArray(value.repositories) || !Array.isArray(value.milestones) || !record(value.routing)) throw new Error("ProgramManifest repositories, milestones, and routing are required."); exactKeys(value.routing, ["defaults"], "ProgramManifest.routing"); if (!record(value.routing.defaults)) throw new Error("ProgramManifest.routing.defaults must be an object."); const repositories = value.repositories.map((item, i) => repository(item, i)); const milestones = value.milestones.map((item, i) => milestone(item, i, repositories)); const ids = new Set(milestones.map((item) => item.id)); for (const item of milestones) for (const dependency of item.dependsOn ?? []) if (!ids.has(dependency)) throw new Error(`Milestone ${item.id} declares unknown dependency ${dependency}.`); return { version: PROGRAM_MANIFEST_VERSION, programId: value.programId, repositories, milestones, routing: { defaults: routes(value.routing.defaults, "ProgramManifest.routing.defaults") } }; }
function repository(value: unknown, index: number) { if (!record(value)) throw new Error(`repositories[${index}] must be an object.`); exactKeys(value, ["id", "owner", "name"], `repositories[${index}]`); string(value.id, "repository.id"); string(value.owner, "repository.owner"); string(value.name, "repository.name"); return { id: value.id, owner: value.owner, name: value.name }; }
function milestone(value: unknown, index: number, repositories: Array<{id:string}>) { if (!record(value)) throw new Error(`milestones[${index}] must be an object.`); exactKeys(value, ["id", "repositoryId", "dependsOn", "routing"], `milestones[${index}]`); string(value.id, "milestone.id"); string(value.repositoryId, "milestone.repositoryId"); if (!repositories.some((repository) => repository.id === value.repositoryId)) throw new Error(`Milestone ${value.id} references an unknown repository.`); if (value.dependsOn !== undefined && (!Array.isArray(value.dependsOn) || value.dependsOn.some((dependency) => typeof dependency !== "string" || !dependency.trim()))) throw new Error(`Milestone ${value.id}.dependsOn must contain non-empty strings.`); return { id: value.id, repositoryId: value.repositoryId, ...(value.dependsOn ? { dependsOn: value.dependsOn } : {}), ...(value.routing === undefined ? {} : { routing: routes(value.routing, `milestones[${index}].routing`) }) }; }
function routes(value: unknown, field: string) { if (!record(value)) throw new Error(`${field} must be an object.`); for (const key of Object.keys(value)) if (key !== "architect" && key !== "implementer" && key !== "reviewer") throw new Error(`${field} has unknown role ${key}.`); const output: Partial<Record<ExecutionRole, ExecutionRouteInput>> = {}; for (const role of ["architect", "implementer", "reviewer"] as const) if (value[role] !== undefined) { if (!record(value[role])) throw new Error(`${field}.${role} must be an object.`); exactKeys(value[role], ["profileId", "profileAlias", "provider", "model", "effort", "allowFallback"], `${field}.${role}`); const route = { ...value[role], allowFallback: value[role].allowFallback ?? false } as ExecutionRouteInput; validateRequestedExecution({ profileId: route.profileId, profileAlias: route.profileAlias, provider: route.provider, model: route.model, effort: route.effort, allowFallback: route.allowFallback ?? false, role }); output[role] = route; } return output; }
function record(value: unknown): value is Record<string, any> { return typeof value === "object" && value !== null && !Array.isArray(value); } function string(value: unknown, field: string): asserts value is string { if (typeof value !== "string" || !value.trim()) throw new Error(`${field} must be a non-empty string.`); } function exactKeys(value: Record<string, unknown>, allowed: string[], field: string): void { for (const key of Object.keys(value)) if (!allowed.includes(key)) throw new Error(`${field} has unknown field ${key}.`); }
export function requestedExecutionFor(manifest: ProgramManifest, milestoneId: string, role: ExecutionRole): RequestedExecution { const milestone = manifest.milestones.find((item) => item.id === milestoneId); if (!milestone) throw new Error(`Unknown milestone ${milestoneId}.`); const route = milestone.routing?.[role] ?? manifest.routing.defaults[role]; if (!route) throw new Error(`No routing configured for ${role} on milestone ${milestoneId}.`); return { profileId: route.profileId, profileAlias: route.profileAlias, provider: route.provider, model: route.model, effort: route.effort, role, allowFallback: route.allowFallback ?? false }; }
